[build-system]
requires = ["setuptools>=75.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "synthwave"
version = "0.1.0"
description = "Population dynamics"
license = "AGPL-3.0-only"
authors = [
    "Vladimir Khodygo <vladimir.khodygo@glasgow.ac.uk>",
]
