[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "mortality_module"
version = "0.0.1"
description = "Population dynamics"
license = " 	AGPL-3.0-only"
authors = [
    "Vladimir Khodygo <vladimir.khodygo@glasgow.ac.uk>",
]