name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.12']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install -U tox
    - name: Test
      run: python -m tox -e py
